apiVersion: apps/v1
kind: Deployment
metadata:
  name: collatz-consumer-deployment
  labels:
    app: consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - image: ashishmahamuni/collatz-consumer
          name: consumer