apiVersion: apps/v1
kind: Deployment
metadata:
  name: collatz-producer-deployment
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - image: ashishmahamuni/collatz-producer
          name: producer